#Lotus Laverne Hotel - Cài \u0111\u1EB7t h\u1EC7 th\u1ED1ng
#Tue May 05 22:01:06 ICT 2026
hotel.address=123 Nguy\u1EC5n Hu\u1EC7, Q.1, TP.HCM
hotel.email=info@lotuslaverne.vn
hotel.name=Lotus Laverne Hotel
hotel.phone=(028) 3822 1234
hotel.rooms=31 ph\u00F2ng
hotel.website=www.lotuslaverne.vn
notif.checkin=true
notif.checkout=true
notif.daily=true
notif.payment=true
notif.sysalert=false
notif.weekly=true
sec.2fa=false
sec.accesslog=true
sec.encrypt=true
sec.pwdchange=90 ng\u00E0y
sec.session=60 ph\u00FAt
sys.backup=H\u00E0ng Ng\u00E0y 02\:00
sys.currency=VND (\u20AB)
sys.dateformat=dd/MM/yyyy
sys.language=Ti\u1EBFng Vi\u1EC7t
sys.timezone=GMT+7 (H\u00E0 N\u1ED9i)
sys.version=v1.0.0
